---

- hosts: localhost

  tasks:

  - name: Install packages
    become: true
    become_user: root
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - git
      - curl
      - vim
      - apt-transport-https
      - ca-certificates
      - maven

  - name: Upgrade all packages
    become: yes
    become_user: root
    apt: 
      upgrade: dist
