---

- hosts: localhost

  tasks:

  - name: Install packages
    state: latest
    become: true
    apt:
     name: "{{ item }}"
     with_items:
      - curl
      - vim
      - apt-transport-https
      - ca-certificates

  - name: Upgrade all packages
    become: yes
    become_user: root
    apt: upgrade=yes
