---

- hosts: localhost

  tasks:

  - name: Install packages
    become: yes
    become_user: root
    apt:
      name:
      - tree
      - htop
      - zsh
      - git
      - curl
      - vim
      - apt-transport-https
      - ca-certificates
      - maven

  - name: fetch fzf from github
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      dest: ~/.fzf
      version: HEAD

  - name: run fzf install script
    script: ~/.fzf/install --all
