---

- hosts: localhost

  tasks:

  - name: Add key to Google Linux repository on dl.google.com.
    become: yes
    apt_key:
     url: https://dl-ssl.google.com/linux/linux_signing_key.pub
     state: present

  - name: Add Google linux repository
    become: yes
    apt_repository:
     repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
     state: present

  - name: Install Google Chrome
    become: yes
    apt:
     name: google-chrome-stable
     update_cache: yes


  