- name: Node.js | Run the debian setup.
  shell: "curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -"
  sudo: yes
  tags: nodejs

- name: Node.js | Install nodejs and npm
  apt: pkg={{ item }} state=present update_cache=yes
  sudo: yes
  tags: nodejs
  with_items:
    - nodejs