---
- hosts: localhost
  tasks:

    - name: Node.js | Run the debian setup.
      shell: "curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -"
      tags: nodejs

    - name: Node.js | Install nodejs and npm
      apt: pkg={{ item }} state=present update_cache=yes
      become: yes
      become_user: root
      tags: nodejs
      with_items:
        - nodejs
