---

- hosts: localhost

  tasks:

  - name: Install zsh
    become: yes
    apt:
     name: zsh
     state: present

  - name: Set zsh as default
    become: yes
    user: 
     name: "{{ ansible_user_id }}"
     shell: /usr/bin/zsh

  - name: Cloning  oh-my-zsh
    git:
     repo: https://github.com/robbyrussell/oh-my-zsh
     dest: ~/.oh-my-zsh

  - name: Creating new ~/.zshrc
    copy:
     src: ~/.oh-my-zsh/templates/zshrc.zsh-template
     dest: ~/.zshrc