---

- hosts: localhost

  tasks:

  - name: Install zsh
    become: yes
    apt:
     name: zsh
     state: present

  - name: Set zsh as default
    become: yes
    user: 
     name: $USER
     shell: /usr/bin/zsh