---

- hosts: localhost

  tasks:

  - name: Install zsh
    become: yes
    apt:
     name: zsh
     state: present

  - name: Fetch oh-my-zsh
    get_url:
     url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
     dest: /tmp/install-oh-my-zsh.sh
     mode: 0755

  - name: Install oh-my-zsh
    command: zsh /tmp/install-oh-my-zsh.sh