---

- hosts: localhost

  tasks:

  - name: Download postman
    get_url:
     url: https://dl.pstmn.io/download/latest/linux64
     dest: /tmp/postman.tar.gz

  - name: Unpack postman
    unarchive:
      src: /tmp/postman.tar.gz
      dest: /opt/postman